### ISSUE TITLE
Identity Access Mnagement is not working in Azure rest all is working as per CIS help needed immediately

### ISSUE THREAD

**Issue by challs1** [SecurityFTW/cs-suite#32]
It was working for everything rather than For Identity Access Management in Azure

**Comment by shivankar-madaan** [comment]
Hi
I didn't quite get issue, could you please elaborate further on it.

**Comment by challs1** [comment]
@shivankar-madaan when I am able to run sudo  python cs.py -env azure it was running from 2.1 to 8 but not from 1.0 which 1.0 is IAM it was not running IAM rules and rest of them are working as expected

**Comment by shivankar-madaan** [comment]
Oh.. Got it!!

We haven't implemented the Azure IAM rules, since most of checks are done manually
You can verify that from the official CIS benchmark PDF from AZURE

https://azure.microsoft.com/mediahandler/files/resourcefiles/cis-microsoft-azure-foundations-security-benchmark/CIS_Microsoft_Azure_Foundations_Benchmark_v1.0.0.pdf

If you come across any document, which can help us implement it via code/automation, please let us know.

Thanks

**Comment by challs1** [comment]
@shivankar-madaan Perfect Thanks for your time and help we can close the issue.

**Comment by shivankar-madaan** [comment]
@challs1 happy to help!!
